name: 📦 Publish to npm & GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

#      - name: Auth to npm (npmjs)
#        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Auth to GitHub Packages
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}

      - name: Install deps
        run: npm ci

      - name: Build / Test (optionnel)
        run: npm run build && npm test || true

      - name: Publish to npmjs
        run: npm publish --access public

      - name: Publish to GitHub Packages
        run: |
          npm publish --registry=https://npm.pkg.github.com/
