name: 📦 Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set GitHub Packages auth
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build (si nécessaire)
        run: npm run build || echo "no build step"

      - name: Publish to GitHub Packages
        run: npm publish